// <auto-generated />
namespace KeJianApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_enterprise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_enterprise));
        
        string IMigrationMetadata.Id
        {
            get { return "201805161604598_Add_enterprise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
